Traceback (most recent call last):
  File "/home/u034/stevenkerr/Git/wp5-clustering/Code/clinical/GMMclustering.py", line 33, in <module>
    data = pd.read_csv(path, index_col=0)
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/parsers.py", line 1862, in __init__
    self._open_handles(src, kwds)
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/parsers.py", line 1357, in _open_handles
    self.handles = get_handle(
  File "/home/u034/stevenkerr/conda-environments/r_env/lib/python3.9/site-packages/pandas/io/common.py", line 639, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'Y:/shared/data/wp-5/clinical_imputation/imputed_datasets/imputed_dataset_1.csv'
